name: Send Email

on: push

jobs:
  mail:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello world
      run: echo "Hello world"

    - name: Send email
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "GitHub Action Notification"
        body: "Job ${{ github.job }} in workflow ${{ github.workflow }} has ${{ job.status }}"
        to: rgkumar1233@example.com
        from: GitHub Actions <${{ secrets.EMAIL_USERNAME }}>
