name: sendmail.yml
on: push

jobs:
  mail:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello world
      run: echo "Hello world"

    - name: sending a mail
      if: $ {{ always() }} 
      uses: devellany/send-mailer@v1.0.2
      with:
          sever_address: smtp.gmail.com
          sever_port: 465
   
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}

          subject: ${{ github.job }} job of ${{ github.repository }} has $ {{ job.status }}
          body: ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          to: rgkumar1233@gmail.com, abcd@gmail.com
          from: Kumaresh 